# 3주차 강의정리

<aside>
✅ 이전 내용

Multinomial classification
: n개의 class로 분류를 할 때 n개의 독립된 clasifier들을 가지고 구현이 가능함.

Hypothesis를 구하기 위한 벡터 연산 표현
→

![image](https://user-images.githubusercontent.com/92504386/196467214-b14eeda6-963d-4b2a-b010-c11bff7244f5.png)


</aside>

## lec 6-1.

Logistic classifier를 벡터로 표현해서 계산하게 되면, 입력값에 대해 A로 분류될 값, B로 분류될 값, C로 분류될 값이 나오게 됨. 

이때 예측값을 0과 1사이의 값의 확률로 표현하고 이들의 합이 1이 되게끔 표현하고자 함.

이때 필요한 것이 Softmax 함수임.

![image](https://user-images.githubusercontent.com/92504386/196467825-38b629a6-780c-48b3-8130-c05ebdb3dbb9.png)

## Softmax Regression

### Softmax 함수

: 소프트맥스는 **세 개 이상으로 분류하는 다중 클래스 분류에서 사용되는 활성화 함수**다. 소프트맥스 함수는 분류될 클래스가 n개라 할 때, n차원의 벡터를 입력받아, 각 클래스에 속할 확률을 추정한다

### One - Hot Encoding

: softmax함수를 통해 나온 예측값 중 가장 큰 값을 1.0으로 만들고, 나머지는 0으로 하는 기법

→ 텐서플로우의 ‘argmax’ 함수를 통해 encoding 가능

예측 값과 실제값의 차이 Cosf function의 값을 작게 훈련시킴으로써 모델 학습.

### Cross-Entropy

softmax함수를 통해서 얻어낸 예측값 s(y)=Y’ 실제 값 Y   

두 값 사이의 차이를 cross-entropy 함수를 통해 구함.

$D(Y’, Y) = - ∑ Yi * log(Y’i)$ 

→ Y’i : softmax를 통해 얻은 값이므로 항상 0~1 사이의 값만을 가짐.

→  $-log(Y’i)$ (← logistic regression) 0일 때는 무한대에 가깝게 가고, y의 값이 1에 가까워질 수록 0에 가까워짐.

- cost function의 궁극적인 목표 : 예측이 맞을 때는 값을 작게, 예측이 틀릴 때는 값을 크게 해줌.
    
     틀리면 ∞, 맞으면 0
    


![image](https://user-images.githubusercontent.com/92504386/196468064-7811b5c7-796a-4a1a-ba48-be1afeb92e32.png)



Loss function을 이용해서

여러개의 training set이 있을 때는 전체의 차이를 구한 후 평균을 내줌.

![image](https://user-images.githubusercontent.com/92504386/196468255-8ec3b292-3710-4cdc-83c4-0d64fbe23e84.png)

마지막 단계)

Gradient descent

cost 를 최소화 하는 w,b를 찾는 Gradient descent 기법 이용.

In [1]:
import tensorflow as tf
import numpy as np


tf.executing_eagerly()
#tf.set_random_seed(777)  # for reproducibility
tf.random.set_seed(777)


In [2]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

#convert into numpy and float format
x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

nb_classes = 3

cross entropy = Y * log(Y_hat)

In [3]:
W = tf.Variable(tf.random.normal([4, nb_classes]), name='wegiht')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')

variables = [W,b]

In [4]:
#cross entropy cost / loss

# cost함수 최소화
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1.minimize(cost))

NameError: name 'Y' is not defined

In [5]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

print(hypothesis(x_data))

tf.Tensor(
[[1.36571964e-02 7.90162385e-03 9.78441238e-01]
 [3.92597765e-02 1.70347411e-02 9.43705440e-01]
 [3.80385250e-01 1.67723164e-01 4.51891571e-01]
 [3.23390484e-01 5.90759404e-02 6.17533624e-01]
 [3.62997389e-06 6.20727292e-08 9.99996305e-01]
 [2.62520202e-02 1.07279625e-02 9.63019967e-01]
 [1.56525111e-05 4.21802753e-07 9.99983907e-01]
 [2.94076904e-06 3.81133276e-08 9.99997020e-01]], shape=(8, 3), dtype=float32)


In [6]:
print(x_data.shape)
print(y_data.shape)

(8, 4)
(8, 3)


In [7]:
# Softmax onehot test
sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype=np.float32)

print(hypothesis(sample_db))

tf.Tensor([[0.9302204  0.06200533 0.00777428]], shape=(1, 3), dtype=float32)


In [8]:
def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_sum(Y * tf.math.log(logits), axis=1)
    cost_mean = tf.reduce_mean(cost)
    
    return cost_mean

print(cost_fn(x_data, y_data))

tf.Tensor(6.07932, shape=(), dtype=float32)


In [9]:
def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y)
        grads = tape.gradient(loss, variables)

        return grads

print(grad_fn(x_data, y_data))

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.06914607, -0.6509784 ,  0.5818323 ],
       [-1.5221257 , -1.214863  ,  2.7369885 ],
       [-1.2473828 , -1.7611003 ,  3.008483  ],
       [-1.2014606 , -1.8659233 ,  3.0673838 ]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.15212913, -0.34219202,  0.4943211 ], dtype=float32)>]


In [10]:

import tensorflow.compat.v1 as tf

def fit(X, Y, epochs=2000, verbose=100):
    #optimizer =  tf.train.GradientDescentOptimizer(learning_rate=0.1)
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
    

    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0):
            print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))
            
fit(x_data, y_data)

Loss at epoch 1: 5.682034
Loss at epoch 100: 1.067572
Loss at epoch 200: 0.741777
Loss at epoch 300: 0.662876
Loss at epoch 400: 0.630050
Loss at epoch 500: 0.606943
Loss at epoch 600: 0.587981
Loss at epoch 700: 0.571635
Loss at epoch 800: 0.557224
Loss at epoch 900: 0.544342
Loss at epoch 1000: 0.532706
Loss at epoch 1100: 0.522104
Loss at epoch 1200: 0.512375
Loss at epoch 1300: 0.503388
Loss at epoch 1400: 0.495040
Loss at epoch 1500: 0.487248
Loss at epoch 1600: 0.479941
Loss at epoch 1700: 0.473063
Loss at epoch 1800: 0.466564
Loss at epoch 1900: 0.460404
Loss at epoch 2000: 0.454548


# Lab 6-2

In [11]:
import tensorflow as tf
import numpy as np
#tf.enable_eager_execution()
tf.random.set_seed(777)

#tfe = tf.contrib.eager

In [12]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.int32) #tf1.13.1에서는 np.int32, 이전에는 np.float32
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(xy)

[[1 0 0 ... 0 1 0]
 [1 0 0 ... 0 1 0]
 [0 0 1 ... 0 0 3]
 ...
 [1 0 0 ... 0 1 0]
 [0 0 1 ... 0 0 6]
 [0 1 1 ... 0 0 1]]


In [13]:

nb_classes = 7  # 0 ~ 6

# Make Y data as onehot shape
Y_one_hot = tf.one_hot(list(y_data), nb_classes)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])

print(x_data.shape, Y_one_hot.shape)

(101, 16) (101, 7)


In [20]:
#Weight and bias setting
W = tf.Variable(tf.random.normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')
variables = [W, b]

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
def logit_fn(X):
    return tf.matmul(X, W) + b

def hypothesis(X):
    return tf.nn.softmax(logit_fn(X))

def cost_fn(X, Y):
    logits = logit_fn(X)
    cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,
                                                           labels=Y)
    cost = tf.reduce_mean(cost_i)
    
    return cost

def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y)
        grads = tape.gradient(loss, variables)
        return grads
    
def prediction(X, Y):
    pred = tf.argmax(hypothesis(X), 1)
    correct_prediction = tf.equal(pred, tf.argmax(Y, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

    return accuracy

In [21]:
print(x_data, y_data)


[[1 0 0 ... 0 0 1]
 [1 0 0 ... 1 0 1]
 [0 0 1 ... 1 0 0]
 ...
 [1 0 0 ... 1 0 1]
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 1 0 0]] [[0]
 [0]
 [3]
 [0]
 [0]
 [0]
 [0]
 [3]
 [3]
 [0]
 [0]
 [1]
 [3]
 [6]
 [6]
 [6]
 [1]
 [0]
 [3]
 [0]
 [1]
 [1]
 [0]
 [1]
 [5]
 [4]
 [4]
 [0]
 [0]
 [0]
 [5]
 [0]
 [0]
 [1]
 [3]
 [0]
 [0]
 [1]
 [3]
 [5]
 [5]
 [1]
 [5]
 [1]
 [0]
 [0]
 [6]
 [0]
 [0]
 [0]
 [0]
 [5]
 [4]
 [6]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [3]
 [3]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [6]
 [3]
 [0]
 [0]
 [2]
 [6]
 [1]
 [1]
 [2]
 [6]
 [3]
 [1]
 [0]
 [6]
 [3]
 [1]
 [5]
 [4]
 [2]
 [2]
 [3]
 [0]
 [0]
 [1]
 [0]
 [5]
 [0]
 [6]
 [1]]


In [18]:
def fit(X, Y, epochs=2000, verbose=500):
    #optimizer =  tf.train.GradientDescentOptimizer(learning_rate=0.1)
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
    

    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0):
            print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))
            
fit(x_data, y_data)

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:MatMul]

In [27]:
x_data.Matmul


AttributeError: 'numpy.ndarray' object has no attribute 'Matmul'