# **Lec 5. Softmax classification**

## **📖 Multinomial classification : Softmax classification**

 **배경) logistic regression**
 - 기존에 연속적인 numeric한 값으로 표현되는 함수 → sigmoid 함수를 통해 binary 한 값으로 조정
![](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/5efb277c-bb3a-447a-89f5-c0a901c46f0d/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221015T151016Z&X-Amz-Expires=86400&X-Amz-Signature=22a188942837026d8e259b8ae5ad4c75c413ac3191bf1053f1552356f35726b9&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)

**Multinomial classification**
- multinomial : 여러 개의 class가 존재
- binary classification만으로도 multinomial classificaiton 구현이 가능함
	- EX) A, B, C 3가지의 class로 분류할 경우 
		1. Binary 1 : C와 C가 아닌것으로 분류 (C or Not)
		2. Binary 2 : B와 B가 아닌 것 (B or Not)
		3. Binary 3 : A와 A가 아닌 것 (A or Not)
		∴ 3개의 binary classification로 구현 가능
		![](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/cad83e16-c494-4a06-8c9a-a8ab4641a8ce/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221015T152107Z&X-Amz-Expires=86400&X-Amz-Signature=59340a87b504f582b65128cd5104a2ed9e77b22b9b459de3f33748bca14dd7e8&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)
		- A, B, C 관련해 각각 독립된 형태의 벡터로 계산해 도출
![](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/bb0903e9-8eda-4b43-9fa4-8184379cbfc8/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221015T152719Z&X-Amz-Expires=86400&X-Amz-Signature=5e2748d91bda405d8906a0c41793209e4ac9f16066b1393fa59898ab29f69a02&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)
		- But 복잡하기에 하나로 합쳐서 구현 → 원하는 값 A, B, C 관련 가설 값 구함
![](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/e31aa729-0af3-4d87-9553-f5f41934ab5a/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221015T152857Z&X-Amz-Expires=86400&X-Amz-Signature=75fb6269372b84abc9835acdf0a2d6427738d63be6afaa78daabc1d3a92adc9c&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)
			> H_A(x) ∼ Y_A
	
		👉 하나의 vector로 처리하면 한번에 계산 가능하면서 독립된 classification처럼 동작함 
		(즉 하나의 classifier을 여러 개의 독립된 classifier처럼 구현 가능함)

	❓ 그렇다면 중간에 sigmoid 처리는 각각 해줘야 하나? → 얘도 한번에 가능!
		

## 📖 softmax classifier 의 cost function

**결과 벡터 안 Y값들의 범위 축소**
- Logistic classifier에 data X를 줘서 계산하면 각 classifier을 거친 값 Y_A, B, C가 벡터 형태로 도출됨
	- 이때 나오는 값들은 범위 제한 없이 다양
	- 따라서 0~1 범위로 정규화가 필요함
		- ∑(classifier들의 정규화 된 Y값) = 1
	 ✅이렇게 조정해 주는 역할 ⟹ Softmax
	 
📌**Softmax**
- n개의 값을 Softmax에 넣으면 range(0,1) 값들로 변환해 줌 (score → Probabilities)
- **특징**
	1. 결과 값이 0 ~ 1 범위 내 존재
	2. ∑(softmax 결과 값) = 1 
	👉 각각의 결과 값을 확률로 볼 수 있음 (ex. A, B, C가 나올 확률)
- One-Hot Encoding 기법
	- 이 확률들 중 제일 가능성이 높은 한 가지만 알려주도록 처리
	- P값들 중 제일 크기 큰 값 = 1, 나머지 0 처리
	- 이렇게 나온 최종 결과를 통해 가장 가까운 후보를 최종 결정

	> **예측 모델 Hypothesis가 완성됨** 
	→이렇게 예측한 값과 실제 값의 차이가 어느정도인지 나타내는 Cost function 정의 필요 (→ Cost function을 최소화 함으로써 학습 완성)

📌**Cost function**
- Cross-Entropy 사용
![](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/320c32da-ae96-40c1-b87f-e320278a51ee/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221015T164213Z&X-Amz-Expires=86400&X-Amz-Signature=97d372b470e47898c13901efad16bfa13ff3a221702e25bd4fb21ecc9fc94fde&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)
	 - L =실제 값, S(Y) = Softmax를 거쳐 도출된 예측 값
	 - 이 2개의 차이 D(S, L)를 Cross Entropy를 통해 구함
	 
	**📌 Cross-entropy 함수가 cost function에 사용되는 이유**
	- -log(y_i)은 항상 0 ~ 1사이 값을 가짐
	- EX) 2가지 Label이 있다고 가정, L(실제 값=정답) ⟹ B를 예측함
	![](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/cb6512d3-e1c1-44bd-a221-bebb4ebd0939/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221015T165010Z&X-Amz-Expires=86400&X-Amz-Signature=e2d6dc16737045a513ab33e2ec587f7bbadab002871024aa406e46d224d27bf0&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)
	- 예측 가능한 경우 1 : Y의 예측이 [0, 1]로 나온 경우
		- Y가  B를 예측⟹ 맞은 예측
![](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/14c9bc8f-5e24-41e5-9018-692f57ecce47/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221015T165750Z&X-Amz-Expires=86400&X-Amz-Signature=935b89c837db8c9b69f8d6fe9acfe3e8c0f1a5e1afffbb114a9c253c79e271d0&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)
		- cost 함수의 최종 값 0 --- good! 
		
	- 예측 가능한 경우 2: Y의 예측이 [1, 0]로 나온 경우
		- Y가 A를 예
		- 측 ⟹ 틀린 예측, 값을 엄청 크게 만들어서 티냄
	![](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/c99ce0ce-c266-4049-b031-2209cd2655aa/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221015T170036Z&X-Amz-Expires=86400&X-Amz-Signature=b273c868939dd2a1e5163ca040a6ec5128077fb5885038699110f20727e17fc6&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)
		- 따라서 예측 값이 틀린 경우 cost값이 무한대로 증가 --- 예측이 틀림
		
**📌 1개의 데이터가 아닌 n개의 dataset이 주어지는 경우 cost function**
- 전체의 거리(= D )를 구한 뒤 n으로 나눠 평균 구함
![](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/1a4ea154-0799-4209-b458-e4d35fadd2b8/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221015T171206Z&X-Amz-Expires=86400&X-Amz-Signature=39a337a9fff683db812318617b56d5e694885f454c45e66422c8b97b4c67b8a8&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)
- 이렇게 **전체 Loss(= Cost function )** 정의 가능 

## 📖 softmax classifier 의 Gradient descent
- 목적
	- cost를 최소화 하는 W 벡터 찾기 위해 Gradient descent사용
	![](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/44512fb5-0efc-460a-b804-90fcbb84e487/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221015T171620Z&X-Amz-Expires=86400&X-Amz-Signature=52bfdfa976aee69b9e1ae8027bdecb45a0ebed485f81b97a18d2749552e07b88&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)
	- 양상은 logistic function과 동일

# LAB 6-1 : Softmax Classifier 구현

In [1]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(777) 

In [2]:
# x_data = (8*4) -> 4개의 feature
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
# y_data =(8*3) 
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

#convert into numpy and float : 학습에 용이하게 하기 위해 numpy 형태로 변환
x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32) #one-hot 표현 시 y의 개수= label(class)의 개수

nb_classes = 3 #class의 개수
#one-hot encoding 방법 - 제일 큰 값만 1, 나머지는 0으로 표기

In [3]:
#Weight and bias setting     #4:입력되는 값 (x의 값 = 4개) 3: 나가는 값 (y의 값 - class 값)
W = tf.Variable(tf.random.normal((4, nb_classes)), name='weight')
b = tf.Variable(tf.random.normal((nb_classes,)), name='bias') #출력값 - class 개수
variables = [W, b]

In [4]:
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b) #softmax를 이용해 hypothesis 완성하기

print(hypothesis(x_data))

tf.Tensor(
[[1.36571955e-02 7.90162291e-03 9.78441179e-01]
 [3.92597765e-02 1.70347411e-02 9.43705440e-01]
 [3.80385250e-01 1.67723149e-01 4.51891541e-01]
 [3.23390484e-01 5.90759404e-02 6.17533624e-01]
 [3.62997366e-06 6.20727221e-08 9.99996245e-01]
 [2.62520202e-02 1.07279625e-02 9.63019967e-01]
 [1.56525093e-05 4.21802724e-07 9.99983847e-01]
 [2.94076904e-06 3.81133241e-08 9.99996960e-01]], shape=(8, 3), dtype=float32)


In [5]:
# Softmax onehot test
sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype=np.float32)

print(hypothesis(sample_db)) #onehot encoding 작동 테스트 (1개만 1 나머진 0)

tf.Tensor([[0.9302204  0.06200533 0.00777428]], shape=(1, 3), dtype=float32)


In [6]:
def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_sum(Y * tf.math.log(logits), axis=1) #가설을 이용해 가설 - 실제값으로 cost함수
    cost_mean = tf.reduce_mean(cost)
    
    return cost_mean

print(cost_fn(x_data, y_data))

tf.Tensor(6.07932, shape=(), dtype=float32)


In [7]:
#이건 그냥 기울기 구하는 with GradientTape() 테스트 - (3,0)에서의 기울기
x = tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x)
    y = x * x # x^2
dy_dx = g.gradient(y, x) # Will compute to 6.0
print(dy_dx)

tf.Tensor(6.0, shape=(), dtype=float32)


In [8]:
#Gradient Function 구성
def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y) #loss = 사전에 정의한 cost function 
        grads = tape.gradient(loss, variables) #grads = gradient(loss, (W, b)값)로 grad 구하기

        return grads

print(grad_fn(x_data, y_data)) #경사 변화량확인 가능

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.06914607, -0.6509784 ,  0.5818323 ],
       [-1.5221257 , -1.214863  ,  2.7369885 ],
       [-1.2473829 , -1.7611003 ,  3.0084827 ],
       [-1.2014607 , -1.8659232 ,  3.0673835 ]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.15212914, -0.342192  ,  0.49432108], dtype=float32)>]


In [10]:
# 위에서 구현한 함수 기반으로 학습모델 생성하는 fit 함수 정의

def fit(X, Y, epochs=2000, verbose=100):
    optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1) #optimizer 정의 (learning rate = 0.1)
    #gradient 사용해 값 업데이트 해줌
    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0): #100번마다 loss값 출력하며 진행방향 올바른지 체크
            print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))
            
fit(x_data, y_data)

Loss at epoch 1: 0.159427
Loss at epoch 100: 0.154003
Loss at epoch 200: 0.148872
Loss at epoch 300: 0.144060
Loss at epoch 400: 0.139539
Loss at epoch 500: 0.135282
Loss at epoch 600: 0.131269
Loss at epoch 700: 0.127480
Loss at epoch 800: 0.123896
Loss at epoch 900: 0.120502
Loss at epoch 1000: 0.117282
Loss at epoch 1100: 0.114226
Loss at epoch 1200: 0.111319
Loss at epoch 1300: 0.108553
Loss at epoch 1400: 0.105917
Loss at epoch 1500: 0.103402
Loss at epoch 1600: 0.101001
Loss at epoch 1700: 0.098706
Loss at epoch 1800: 0.096510
Loss at epoch 1900: 0.094407
Loss at epoch 2000: 0.092391


## Prediction
: 학습 후 Hypothesis를 통해 직접 예측

In [11]:
# 예시용 샘플 데이터
sample_data = [[2,1,3,2]] # answer_label [[0,0,1]]
sample_data = np.asarray(sample_data, dtype=np.float32)

In [12]:
# 각각의 예측값에서 가장 높은 값을 뽑기 예시  - one hot encoding
# hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
a = hypothesis(sample_data)

print(a)
#나온 확률 값 중 가장 높은 값 선택 -> argmax
print(tf.argmax(a, 1)) #index: 2 -> [0, 0, 1]

tf.Tensor([[4.3665306e-04 4.6358623e-02 9.5320475e-01]], shape=(1, 3), dtype=float32)
tf.Tensor([2], shape=(1,), dtype=int64)


In [13]:
#x_data로 적용

b = hypothesis(x_data)
print(b)
print(tf.argmax(b, 1))
print(tf.argmax(y_data, 1)) # Y와 일치함 - 학습 정상적으로 완료

tf.Tensor(
[[2.9436805e-08 1.5021235e-04 9.9984980e-01]
 [4.3665289e-04 4.6358626e-02 9.5320481e-01]
 [9.5460018e-10 9.6164070e-02 9.0383589e-01]
 [2.2774371e-07 9.1306245e-01 8.6937323e-02]
 [1.6050829e-01 8.3273548e-01 6.7562237e-03]
 [8.4970415e-02 9.1502690e-01 2.6765201e-06]
 [8.2284725e-01 1.7714940e-01 3.2996732e-06]
 [9.6834594e-01 3.1654030e-02 1.4558012e-08]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


# LAB 6-2 : Softmax Classifier Animal Classification
: softmax classifier을 통해 동물 분류 해보기
    - softmax_cross_entropy_with_logits 사용

In [2]:
#Sample dataset 준비
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1] #마지막 column 제외한 만큼
y_data = xy[:, -1]

nb_classes = 7  # 클래스 숫자 정의 : 0 ~ 6 , 총 7종으로 분류 -> 종 예측

#데이터 전처리
# Y값 one-hot 형태로 변형 - tf.one_hot - 이 과정에서 차원 +1
Y_one_hot = tf.one_hot(y_data.astype(np.int32), nb_classes) #astype으로 reshape

print(x_data.shape, Y_one_hot.shape)

(101, 16) (101, 7)


- softmax classifier 구현

In [3]:
#1. Weight and bias 세팅
W = tf.Variable(tf.random.normal((16, nb_classes)), name='weight')
b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
variables = [W, b] #weight와 bias 업데이트할 variable 별도로 지정

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
def logit_fn(X):
    return tf.matmul(X, W) + b

def hypothesis(X):
    return tf.nn.softmax(logit_fn(X))
#logit 사용
def cost_fn(X, Y):
    logits = logit_fn(X)
    cost_i = tf.keras.losses.categorical_crossentropy(y_true=Y, y_pred=logits, 
                                                      from_logits=True)    
    cost = tf.reduce_mean(cost_i)    
    return cost
#gradient 구함 
def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y)
        grads = tape.gradient(loss, variables) #W,b 사용
        return grads
#단순 loss 뿐만 아니라 정확도도 계산 (hypothesis 사용됨)
def prediction(X, Y):
    pred = tf.argmax(hypothesis(X), 1)
    correct_prediction = tf.equal(pred, tf.argmax(Y, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

    return accuracy

### Implementation - training
: 구현한 softmax 학습하는 함수


In [5]:
def fit(X, Y, epochs=1000, verbose=100):
    optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)

    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0):
            acc = prediction(X, Y).numpy() #prediction 함수를 통해 정확도까지 출력
            loss = cost_fn(X, Y).numpy() 
            print('Steps: {} Loss: {}, Acc: {}'.format(i+1, loss, acc))

fit(x_data, Y_one_hot)

Steps: 1 Loss: 3.635028839111328, Acc: 0.1683168262243271
Steps: 100 Loss: 0.5194157958030701, Acc: 0.7920792102813721
Steps: 200 Loss: 0.31850090622901917, Acc: 0.9108911156654358
Steps: 300 Loss: 0.23534879088401794, Acc: 0.9405940771102905
Steps: 400 Loss: 0.18872138857841492, Acc: 0.9504950642585754
Steps: 500 Loss: 0.15846037864685059, Acc: 0.9504950642585754
Steps: 600 Loss: 0.13703757524490356, Acc: 0.9900990128517151
Steps: 700 Loss: 0.12098980695009232, Acc: 0.9900990128517151
Steps: 800 Loss: 0.10847964882850647, Acc: 1.0
Steps: 900 Loss: 0.09843041002750397, Acc: 1.0
Steps: 1000 Loss: 0.09016557037830353, Acc: 1.0
